import bcrypt from 'bcryptjs'

const data = {
    users: [
        {
            name:'Mayara',
            email: 'admin@exemple.com',
            password: bcrypt.hashSync('1234',8),
            isAdmin: true,
        },
        {
            name:'Maria',
            email: 'user@exemple.com',
            password: bcrypt.hashSync('1234',8),
            isAdmin: false,
        },

    ],
    products: [
        {
            _id:'1',
            name:'Perfume Dolce e Gabbana',
            category: 'Perfumes',
            image:'/images/p7.jpg',
            price:390,
            countInStock: 10,
            brand:'Dolce e Gabbana',
            rating:4.5,
            numReviews:10,
            description:'Ótima qualidade',
        },
        {
            _id:'2',
            name:'Perfume Giorgio Armani Si',
            category: 'Perfumes',
            image:'/images/p8.jpg',
            price:450,
            countInStock: 20,
            brand:'Giorgio Armani',
            rating:4.5,
            numReviews:10,
            description:'Ótima qualidade',
        },
        {
            _id:'3',
            name:'Perfume Chanel nº5',
            category: 'Perfumes',
            image:'/images/p9.jpg',
            price:400,
            countInStock: 28,
            brand:'Chanel',
            rating:4.5,
            numReviews:10,
            description:'Ótima qualidade',
        },
        {
            _id:'4',
            name:'Batom matte Vult',
            category: 'Maqiagem',
            image:'/images/p10.jpg',
            price:20,
            countInStock: 10,
            brand:'Vult',
            rating:4.5,
            numReviews:10,
            description:'Ótima qualidade',
        },
        {
            _id:'5',
            name:'Batom Nars',
            category: 'Maquiagem',
            image:'/images/p11.jpg',
            price:120,
            countInStock: 100,
            brand:'Nars',
            rating:4.5,
            numReviews:10,
            description:'Ótima qualidade',
        },
        {
            _id:'6',
            name:'Creme TreSemmé',
            category: 'Cabelos',
            image:'/images/p12.jpg',
            price:15,
            countInStock: 87,
            brand:'TreSemmé',
            rating:4.5,
            numReviews:10,
            description:'Ótima qualidade',
        },
        {
            _id:'7',
            name:'Creme Pantene',
            category: 'Cabelos',
            image:'/images/p13.jpg',
            price:20,
            countInStock: 87,
            brand:'Pantene',
            rating:4.5,
            numReviews:10,
            description:'Ótima qualidade',
        },
        {
            _id:'8',
            name:'Creme facial Nívea',
            category: 'Creme facial',
            image:'/images/p14.jpg',
            price:30,
            countInStock: 87,
            brand:'Nívea',
            rating:4.5,
            numReviews:10,
            description:'Ótima qualidade',
        },
    ]
};

export default data;